apiVersion: v1
kind: Service
metadata:
  name: pg-master
spec:
  type: NodePort  # Expose via NodePort
  selector:
    app: postgres
    role: master
  ports:
  - protocol: TCP
    port: 5432  # PostgreSQL default port
    nodePort: 30001  # Assign a specific port (optional)

---
# slave-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pg-slave
spec:
  type: NodePort  # Expose via NodePort
  selector:
    app: postgres
    role: slave
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30002  # Assign a specific port (optional)
