# pg-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    wal_level = replica
    max_wal_senders = 3
    wal_keep_segments = 64
    hot_standby = on
  pg_hba.conf: |
    host replication all 0.0.0.0/0 md5
    host all all 0.0.0.0/0 md5

