# pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-master-pv
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pgsql/kube/master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-slave-pv
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pgsql/kube/slave

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-master-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pg-master-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-slave-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pg-slave-pv
