apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-standby-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pgsql/kube/standby1

