apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-standby-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pg-standby-pv

